version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/tomcat/webapps
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate.sh
      timeout: 300
      runas: root
